workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      java: 21
    scripts:
      - name: Install Node.js 22.1.0 via nvm
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 22.1.0
          nvm use 22.1.0
          node --version
          npm --version
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor to Android project
        script: |
          npx cap sync android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Grant execute permissions to gradlew
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android Release AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
